@startuml

/' diagram meta data start
config=CallConfiguration;
{
  "rootMethod": "com.example.nnayyar1_expbook.ExpenseRecord#getMonthStarted()",
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showMethodParametersTypes": false,
    "showMethodParametersNames": false,
    "showMethodReturnType": false,
    "showPackageLevels": 2,
    "showCallOrder": false,
    "edgeMode": "MethodsOnly", // TypesOnly, MethodsOnly, TypesAndMethods, MethodsAndDirectTypeUsage
    "showDetailedClassStructure": false
  },
  "rootClass": "com.example.nnayyar1_expbook.ExpenseRecord",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="LR"
    splines=polyline
    

'nodes 
subgraph cluster_1322970774 { 
   	label=example
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_4760394 { 
   	label=nnayyar1_expbook
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1367754546 { 
   	label=ExpenseListActivity
	labeljust=l
	fillcolor=white
	style=filled
   
   ExpenseListActivity2055537897XXXonItemClick104431[
	label="+ onItemClick()"
	style=filled
	fillcolor=white
	tooltip="ExpenseListActivity

null"
	fontcolor=darkgreen
];
} 

subgraph cluster_1801859090 { 
   	label=ExpenseRecord
	labeljust=l
	fillcolor=white
	style=filled
   
   ExpenseRecord2055537897XXXgetMonthStarted0[
	label="+ getMonthStarted()"
	style=filled
	fillcolor=white
	tooltip="ExpenseRecord

null"
	penwidth=4
	fontcolor=darkgreen
];
} 

subgraph cluster_2084919214 { 
   	label=ExpenseAdapter
	labeljust=l
	fillcolor=white
	style=filled
   
   ExpenseAdapter2055537897XXXonBindViewHolder298551242[
	label="+ onBindViewHolder()"
	style=filled
	fillcolor=white
	tooltip="ExpenseAdapter

null"
	fontcolor=darkgreen
];
} 
} 
} 

'edges    
ExpenseAdapter2055537897XXXonBindViewHolder298551242 -> ExpenseRecord2055537897XXXgetMonthStarted0;
ExpenseListActivity2055537897XXXonItemClick104431 -> ExpenseRecord2055537897XXXgetMonthStarted0;
    
}
@enduml